script: "echo starting..."

deploy:
  provider: s3
  access_key_id: "$ACCESS_KEY_ID"
  secret_access_key: "$SECRET_ACCESS_KEY"
  bucket: "ci.julienbalestra.com"
  skip_cleanup: true
  acl: public_read
  region: eu-west-1
